# THIS IS AN INCOMPLETE PYPROJECT.TOML
# USED BY THE BUILD WHEEL SCRIPT
# TO CREATE A COMPLETE PYPROJECT.TOML.
[project]
version = "1.0.47"
description = "Application indicator which displays the current Star Trekâ„¢ stardate."
classifiers = [
  "Topic :: Games/Entertainment" ]
