# THIS IS AN INCOMPLETE PYPROJECT.TOML
# USED BY THE BUILD WHEEL SCRIPT
# TO CREATE A COMPLETE PYPROJECT.TOML.
[project]
version = "1.0.103"
description = "Application indicator for the home astronomer."
classifiers = [
  "Topic :: Scientific/Engineering :: Astronomy" ]
dependencies = [
  "ephem",
  "sgp4" ]
