# THIS IS AN INCOMPLETE PYPROJECT.TOML
# USED BY THE BUILD WHEEL SCRIPT
# TO CREATE A COMPLETE PYPROJECT.TOML.
[project]
version = "1.0.18"
description = "Application indicator which converts domain names between Unicode and ASCII."
classifiers = [
  "Topic :: Utilities" ]
