# THIS IS AN INCOMPLETE PYPROJECT.TOML
# USED BY THE BUILD WHEEL SCRIPT
# TO CREATE A COMPLETE PYPROJECT.TOML.
[project]
version = "1.0.19"
description = "Application indicator to test indicator functionality."
classifiers = [
  "Topic :: Software Development :: Testing" ]
